#!/bin/bash

echo "🔧 MongoDB Atlas Setup Guide"
echo "=============================="
echo ""
echo "1. Go to MongoDB Atlas: https://cloud.mongodb.com/"
echo "2. Create a new cluster (free tier available)"
echo "3. Create a database user with read/write permissions"
echo "4. Whitelist your IP address (or use 0.0.0.0/0 for all IPs)"
echo "5. Get your connection string"
echo ""
echo "📝 Add to your .env file:"
echo "MONGODB_URI=mongodb+srv://<username>:<password>@<cluster-url>/<database-name>?retryWrites=true&w=majority"
echo ""
echo "Example:"
echo "MONGODB_URI=mongodb+srv://myuser:mypassword@cluster0.abc123.mongodb.net/diwali-postcard?retryWrites=true&w=majority"
echo ""
echo "🔑 Environment Variables Needed:"
echo "- MONGODB_URI: Your MongoDB Atlas connection string"
echo ""
echo "📋 Steps to get your connection string:"
echo "1. In MongoDB Atlas dashboard, click 'Connect' on your cluster"
echo "2. Choose 'Connect your application'"
echo "3. Select 'Node.js' as driver"
echo "4. Copy the connection string"
echo "5. Replace <password> with your database user password"
echo "6. Replace <dbname> with your database name (e.g., 'diwali-postcard')"
echo ""
echo "✅ After setup, your users will be automatically saved to MongoDB Atlas!"
echo ""
